# Generated by Django 4.2.23 on 2026-09-23 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('student_usn', models.CharField(blank=True, max_length=100)),
                ('old_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('dropped', 'Dropped'), ('expelled', 'Expelled'), ('graduated', 'Graduated')], max_length=15)),
                ('new_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('dropped', 'Dropped'), ('expelled', 'Expelled'), ('graduated', 'Graduated')], max_length=15)),
                ('reason', models.TextField(blank=True)),
                ('changed_by_name', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_status_changes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_logs', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Status Log',
                'verbose_name_plural': 'Student Status Logs',
                'ordering': ['-changed_at', '-pk'],
                'indexes': [models.Index(fields=['student', '-changed_at'], name='studentstat_student_30e37c_idx')],
            },
        ),
    ]
