# Generated by Django 4.2.23 on 2025-08-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcategory',
            name='name',
            field=models.CharField(help_text="Name of the payment category (e.g., 'Tuition Fee JSS1', 'Hostel Fee JSS2').", max_length=100, unique=True),
        ),
    ]
