# Generated by Django 4.2.23 on 2025-08-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('curriculum', '0002_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='The actual amount this specific student owes.', max_digits=10)),
                ('category_fee', models.ForeignKey(help_text="The standard fee category this student's fee is based on.", on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='payments.categoryfee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='curriculum.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='curriculum.term')),
            ],
            options={
                'verbose_name': 'Student Fee',
                'verbose_name_plural': 'Student Fees',
                'unique_together': {('student', 'category_fee', 'term', 'session')},
            },
        ),
    ]
