# Generated by Django 4.2.23 on 2025-07-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.CharField(blank=True, help_text='Any additional notes or remarks about the payment.', max_length=100, null=True),
        ),
    ]
