# Generated by Django 4.2.23 on 2025-07-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=1, help_text='The actual amount received in this payment transaction.', max_digits=10),
            preserve_default=False,
        ),
    ]
