# Generated by Django 4.2.23 on 2026-07-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetail',
            name='description',
            field=models.CharField(default=1, max_length=50, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
