# Generated by Django 4.2.23 on 2025-08-28 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
        ('payments', '0002_studentfee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryfee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='categoryfee',
            name='student_class',
            field=models.ForeignKey(blank=True, help_text='The class level this fee applies to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='curriculum.standard'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryfee',
            unique_together={('payment_category', 'term', 'session', 'student_class', 'fee_name')},
        ),
    ]
