# Generated by Django 4.2.23 on 2025-07-14 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_standard_options_alter_subject_options_and_more'),
        ('payments', '0002_remove_payment_amount_payment_amount_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The original amount due for this payment (can be derived from Category Fee or manually set).', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CategoryFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(blank=True, help_text="A specific name for this fee instance (e.g., 'First Semester Tuition').", max_length=255, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='The standard amount due for this category, term, and session.', max_digits=10)),
                ('payment_category', models.ForeignKey(help_text='The payment category this fee applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='payments.paymentcategory')),
                ('session', models.ForeignKey(help_text='The academic session this fee applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='category_fees', to='curriculum.session')),
                ('term', models.ForeignKey(help_text='The academic term this fee applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='category_fees', to='curriculum.term')),
            ],
            options={
                'verbose_name': 'Category Fee',
                'verbose_name_plural': 'Category Fees',
                'ordering': ['session__name', 'term__name', 'payment_category__name', 'fee_name'],
                'unique_together': {('payment_category', 'term', 'session', 'fee_name')},
            },
        ),
    ]
