# Generated by Django 4.2.23 on 2025-08-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirm_payment',
            field=models.BooleanField(blank=True, default=False, verbose_name='confirm the payment'),
        ),
    ]
