# Generated by Django 4.2.23 on 2025-07-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_original_amount_categoryfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance_after_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Balance remaining for this specific CategoryFee after this payment.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='balance_before_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Balance remaining for this specific CategoryFee before this payment.', max_digits=10, null=True),
        ),
    ]
