# Generated by Django 4.2.23 on 2026-08-24 11:12

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics', validators=[users.models.validate_image_max_size], verbose_name='Profile Pic'),
        ),
    ]
