# Generated by Django 4.2.23 on 2025-07-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activate',
            field=models.BooleanField(blank=True, default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('select', 'select'), ('student', 'student'), ('teacher', 'teacher'), ('admin', 'admin'), ('other_staff', 'other_staff'), ('parent', 'parent')], default='select', max_length=20, null=True),
        ),
    ]
