# Generated by Django 4.2.23 on 2025-08-27 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=50, verbose_name='description')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Prefect Badge',
                'verbose_name_plural': 'Prefect Badge',
            },
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('hostel_master', models.ForeignKey(blank=True, help_text='select hostel master', null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=60, null=True)),
                ('guardian_address', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_email', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(help_text='The user account for this parent.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(help_text='Unique Student Number, Must be same as username', max_length=100)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('select_gender', 'select_gender')], default='select_gender', max_length=20)),
                ('DOB', models.DateField(default='1998-01-01')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'B-'), ('B+', 'B+'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('select', 'select')], default='select', max_length=15)),
                ('genotype', models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS'), ('select', 'select')], default='select', max_length=15)),
                ('health_remark', models.CharField(default='enter health detail', max_length=60, null=True)),
                ('student_type', models.CharField(choices=[('day_student', 'day_student'), ('boarder', 'boarder')], default='day_student', max_length=15)),
                ('date_admitted', models.DateField(default='2020-01-01')),
                ('guardian_name', models.CharField(max_length=60, null=True)),
                ('guardian_address', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_email', models.CharField(blank=True, max_length=30, null=True)),
                ('relationship', models.CharField(choices=[('select', 'select'), ('parent', 'parent'), ('father', 'father'), ('mother', 'mother'), ('sister', 'sister'), ('brother', 'brother'), ('aunt', 'aunt'), ('uncle', 'uncle'), ('other', 'other')], default='select', help_text="Guardian's Relationship With Student", max_length=25)),
                ('student_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('graduated', 'graduated'), ('dropped', 'dropped'), ('expelled', 'expelled'), ('suspended', 'suspended')], default='active', max_length=15)),
                ('fee_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.badge', verbose_name='Prefect')),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='curriculum.classgroup')),
                ('class_on_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_on_admission', to='curriculum.standard', verbose_name='class_on_admission')),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='curriculum.standard')),
                ('form_teacher', models.ForeignKey(blank=True, help_text='This field will be automatically updated when form teacher is set in the standard', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='staff.teacher')),
                ('hostel_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_name', to='students.hostel', verbose_name='hostel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='students.parent')),
                ('user', models.OneToOneField(help_text='select user or add a new user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Details',
                'verbose_name_plural': 'Student Details',
                'ordering': ['user'],
            },
        ),
    ]
