# Generated by Django 4.2.23 on 2026-02-06 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name'], 'verbose_name': 'Student Details', 'verbose_name_plural': 'Student Details'},
        ),
        migrations.AlterField(
            model_name='student',
            name='graduated_session',
            field=models.ForeignKey(blank=True, help_text='only applicable for graduated students', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduated_students', to='curriculum.session'),
        ),
    ]
