# Generated by Django 4.2.23 on 2025-08-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
