# Generated by Django 4.2.23 on 2025-08-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='desc',
            field=models.CharField(blank=True, max_length=50, verbose_name='description'),
        ),
    ]
