# Generated by Django 4.2.23 on 2025-08-13 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='hostel_master',
            field=models.ForeignKey(blank=True, help_text='select hostel master', null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.teacher'),
        ),
    ]
