# Generated by Django 4.2.23 on 2026-04-11 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='desc',
        ),
        migrations.AddField(
            model_name='hostel',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Total bed spaces in this hostel'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='description',
            field=models.TextField(blank=True, help_text='Location details or rules'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='gender_type',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('mixed', 'Mixed')], default='mixed', max_length=10),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hostels', to='staff.teacher'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(default='TEMPORARY_NAME', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('max_occupancy', models.PositiveIntegerField(default=4)),
                ('is_available', models.BooleanField(default=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='students.hostel')),
            ],
        ),
    ]
