# Generated by Django 4.2.23 on 2025-08-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_fee_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
