# Generated by Django 4.2.23 on 2026-04-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_hostel_desc_hostel_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostel',
            options={'verbose_name': 'Hostel Reg', 'verbose_name_plural': 'Hostel Reg'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Hostel Rooms', 'verbose_name_plural': 'Hostel Rooms'},
        ),
        migrations.AddField(
            model_name='student',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupants', to='students.room'),
        ),
    ]
