# Generated by Django 4.2.23 on 2025-11-20 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
        ('students', '0002_student_graduated_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_graduated', models.DateTimeField(auto_now_add=True)),
                ('graduated_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.standard')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_records', to='students.student')),
            ],
        ),
    ]
