# Generated by Django 4.2.23 on 2026-04-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_hostel_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assigned_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupants', to='students.room', verbose_name='Assigned Rooom(Hostel)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hostel_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_name', to='students.hostel', verbose_name='Hostel'),
        ),
    ]
