# Generated by Django 4.2.23 on 2026-07-25 22:44

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('curriculum', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text='Show this account first on invoices/receipts.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['-is_primary', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('salaries', 'Staff Salaries & Wages'), ('utilities', 'Utilities (Power, Water, Internet)'), ('maintenance', 'Repairs & Maintenance'), ('supplies', 'Teaching & Office Supplies'), ('transport', 'Transport & Fuel'), ('food', 'Feeding / Catering'), ('marketing', 'Marketing & Admissions'), ('admin', 'Administrative'), ('capital', 'Capital Expenditure (Assets)'), ('tax', 'Taxes & Levies'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Tuition Fee', 'Hostel Fee', 'Bus Fee - Zone A'.", max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('tuition', 'Tuition'), ('hostel', 'Hostel / Boarding'), ('transport', 'Transport'), ('exam', 'Examination'), ('uniform', 'Uniform & Wears'), ('books', 'Books & Learning Materials'), ('feeding', 'Feeding'), ('pta', 'PTA / Development Levy'), ('admission', 'Admission / Registration'), ('other', 'Other')], default='other', help_text='Used to group income for reporting and P&L breakdowns.', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fee Category',
                'verbose_name_plural': 'Fee Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Optional specific label, e.g. 'First Term Tuition - Boarding'.", max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_mandatory', models.BooleanField(default=True, help_text='Uncheck for optional charges (e.g. extra lessons).')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='finance.feecategory')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_fee_structures', to='curriculum.session')),
                ('student_class', models.ForeignKey(blank=True, help_text='Leave blank to apply this fee to ALL classes (e.g. a school-wide PTA levy).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fin_fee_structures', to='curriculum.standard')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_fee_structures', to='curriculum.term')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['session__name', 'term__name', 'student_class__name', 'fee_category__name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='issued', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fin_invoices', to='curriculum.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_invoices', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fin_invoices', to='curriculum.term')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issue_date', '-id'],
                'permissions': [('generate_invoices', 'Can bulk-generate invoices for a class'), ('view_profit_loss', 'Can view Profit & Loss reports'), ('export_financial_reports', 'Can export financial reports (PDF/CSV)')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment'), ('online_gateway', 'Online Gateway'), ('cheque', 'Cheque'), ('mobile_money', 'Mobile Money'), ('pos', 'POS Terminal')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Gateway/bank reference. Auto-generated for manual/cash entries.', max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('balance_before_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balance_after_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('fee_category', models.ForeignKey(help_text='Category this payment is recorded under (auto-filled from invoice if left blank).', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.feecategory')),
                ('invoice', models.ForeignKey(blank=True, help_text='The invoice this payment is settling. Leave blank for a misc. payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fin_payments', to='curriculum.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_payments', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fin_payments', to='curriculum.term')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vendor / Payee',
                'verbose_name_plural': 'Vendors / Payees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('debit', 'Debit (Charge)'), ('credit', 'Credit (Payment)'), ('adjustment', 'Adjustment')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.invoice')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.payment')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fin_ledger_entries', to='curriculum.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_ledger_entries', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fin_ledger_entries', to='curriculum.term')),
            ],
            options={
                'verbose_name': 'Student Ledger Entry',
                'verbose_name_plural': 'Student Ledger Entries',
                'ordering': ['student', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off')], default='percentage', max_length=12)),
                ('value', models.DecimalField(decimal_places=2, help_text='e.g. 20 for 20% off, or a fixed Naira amount off, depending on type.', max_digits=8)),
                ('reason', models.CharField(help_text="e.g. 'Sibling discount', 'Staff ward', 'Merit scholarship - 100%'.", max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_discounts_approved', to=settings.AUTH_USER_MODEL)),
                ('fee_category', models.ForeignKey(blank=True, help_text="Leave blank to apply this discount to ALL fee categories on the student's invoice.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='finance.feecategory')),
                ('session', models.ForeignKey(blank=True, help_text='Leave blank to apply every session (a standing waiver).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fin_discounts', to='curriculum.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_discounts', to='students.student')),
                ('term', models.ForeignKey(blank=True, help_text='Leave blank to apply every term.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fin_discounts', to='curriculum.term')),
            ],
            options={
                'verbose_name': 'Student Discount / Concession',
                'verbose_name_plural': 'Student Discounts / Concessions',
                'ordering': ['student__last_name', '-created_at'],
                'permissions': [('manage_discounts', 'Can grant or revoke student fee discounts')],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_receipts_generated', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='finance.payment')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CASH_DEPOSIT', 'Cash Deposit (Bank)'), ('POS', 'POS Transaction'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other Offline Method')], default='BANK_TRANSFER', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('proof_of_payment', models.FileField(blank=True, help_text='Upload a screenshot/scan of the payment evidence (PDF, JPG or PNG).', null=True, upload_to='finance/payment_proofs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('PROCESSED', 'Processed (Payment Recorded)'), ('REJECTED', 'Rejected (Invalid Proof)')], default='PENDING', max_length=10)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.bankaccount', verbose_name='School Bank Account')),
                ('notified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_payment_notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_payment_notifications_processed', to=settings.AUTH_USER_MODEL)),
                ('resulting_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_notification', to='finance.payment')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fin_payment_notifications', to='curriculum.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_payment_notifications', to='students.student', verbose_name='Student Paid For')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fin_payment_notifications', to='curriculum.term')),
            ],
            options={
                'verbose_name': 'Payment Notification',
                'verbose_name_plural': 'Payment Notifications',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, help_text='The undiscounted fee-structure amount, before any StudentDiscount was applied.', max_digits=12, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total concession/scholarship reduction applied to this line.', max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Final payable line total (already net of any discount).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('applied_discount', models.ForeignKey(blank=True, help_text='The discount rule that produced discount_amount, if any (for audit trail).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='finance.studentdiscount')),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='finance.feecategory')),
                ('fee_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='finance.feestructure')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'ordering': ['fee_category__name'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_installment_plans_created', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan', to='finance.invoice')),
            ],
            options={
                'verbose_name': 'Installment Plan',
                'verbose_name_plural': 'Installment Plans',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(help_text='Order of this installment, e.g. 1, 2, 3.')),
                ('label', models.CharField(help_text="e.g. '1st Installment', 'Resumption Payment'.", max_length=100)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_date', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.installmentplan')),
            ],
            options={
                'verbose_name': 'Installment',
                'verbose_name_plural': 'Installments',
                'ordering': ['plan', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short description, e.g. 'July diesel purchase'.", max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment'), ('online_gateway', 'Online Gateway'), ('cheque', 'Cheque'), ('mobile_money', 'Mobile Money'), ('pos', 'POS Terminal')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Cheque no. / transfer ref, etc.', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='paid', max_length=10)),
                ('attachment', models.FileField(blank=True, help_text='Optional receipt/invoice from the vendor (PDF, JPG or PNG).', null=True, upload_to='finance/expense_receipts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_expenses_recorded', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_expenses', to='curriculum.session')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_expenses', to='curriculum.term')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.vendor')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date', '-id'],
                'permissions': [('approve_expense', 'Can approve or reject expenses')],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('exclude', 'Exclude (do not charge this student)'), ('include', 'Include (charge this student even though it is optional/not default)')], max_length=10)),
                ('reason', models.CharField(help_text="e.g. 'Returning student — registration fee waived', 'Requested extra uniform set, Term 2'.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_fee_exceptions_created', to=settings.AUTH_USER_MODEL)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exceptions', to='finance.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_fee_exceptions', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Fee Exception',
                'verbose_name_plural': 'Student Fee Exceptions',
                'ordering': ['student__last_name', '-created_at'],
                'unique_together': {('student', 'fee_structure')},
            },
        ),
        migrations.CreateModel(
            name='StudentAccountLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fin_student_ledgers', to='curriculum.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_account_ledgers', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fin_student_ledgers', to='curriculum.term')),
            ],
            options={
                'verbose_name': 'Student Account Ledger',
                'verbose_name_plural': 'Student Account Ledgers',
                'ordering': ['student__last_name', 'session__name', 'term__name'],
                'unique_together': {('student', 'term', 'session')},
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'term', 'session'], name='finance_pay_student_bb7669_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'payment_date'], name='finance_pay_status_549635_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('student', 'term', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('plan', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('student_class', 'fee_category', 'term', 'session', 'label')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='finance_exp_expense_a60cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'expense_date'], name='finance_exp_categor_b624d6_idx'),
        ),
    ]
