# Generated by Django 4.2.23 on 2026-08-23 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now=True)),
                ('notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='finance.paymentnotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_read_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Read Status',
                'verbose_name_plural': 'Notification Read Statuses',
                'unique_together': {('user', 'notify')},
            },
        ),
    ]
