# Generated by Django 4.2.23 on 2026-08-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_notificationreadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnotification',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes, include depositor name'),
        ),
    ]
