# Generated by Django 4.2.23 on 2026-08-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_paymentnotification_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnotification',
            name='notes',
            field=models.TextField(blank=True, help_text='include depositor name in the note'),
        ),
    ]
