# Generated by Django 4.2.23 on 2026-07-27 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Do not enter anything here', null=True)),
            ],
            options={
                'verbose_name': 'Staff Roles',
                'verbose_name_plural': 'Staff Roles',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('select_gender', 'select_gender')], default='select_gender', max_length=20)),
                ('DOB', models.DateField(default='1998-01-01')),
                ('date_employed', models.DateField(default='1998-01-01')),
                ('marital_status', models.CharField(choices=[('married', 'married'), ('single', 'single'), ('select', 'select')], default='select', max_length=15)),
                ('phone_home', models.CharField(blank=True, max_length=11, null=True)),
                ('qualification', models.CharField(default='OND', max_length=150)),
                ('year', models.DateField(default='1998-01-01')),
                ('institution', models.CharField(blank=True, max_length=150)),
                ('professional_body', models.CharField(blank=True, max_length=150)),
                ('guarantor_name', models.CharField(blank=True, max_length=150)),
                ('guarantor_phone', models.CharField(blank=True, max_length=15)),
                ('guarantor_address', models.CharField(blank=True, max_length=150)),
                ('guarantor_email', models.CharField(blank=True, max_length=60)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=60)),
                ('next_of_kin_address', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=15)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(blank=True, default=False)),
                ('dept', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_dept', to='users.dept')),
                ('staff_role', models.ForeignKey(blank=True, default='select', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_role', to='staff.staffposition')),
                ('standards_assigned', models.ManyToManyField(blank=True, related_name='teachers', to='curriculum.standard')),
                ('subjects_taught', models.ManyToManyField(related_name='teachers', to='curriculum.subject')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teachers & Staff Details',
                'verbose_name_plural': 'Teachers & Staff Details',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('excused', 'Excused'), ('half_day', 'Half Day')], default='present', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_checked_in', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_checked_out', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff.teacher')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
