# Generated by Django 4.2.23 on 2025-08-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='standards_assigned',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='curriculum.standard'),
        ),
    ]
