# Generated by Django 4.2.23 on 2026-05-26 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0002_staffattendancesession_staffattendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffattendance',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='staffattendance',
            name='marked_by',
        ),
        migrations.RemoveField(
            model_name='staffattendance',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_checked_in', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_checked_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staffattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('excused', 'Excused'), ('half_day', 'Half Day')], default='present', max_length=20),
        ),
        migrations.DeleteModel(
            name='StaffAttendanceSession',
        ),
    ]
