# Generated by Django 4.2.23 on 2026-06-03 11:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aitoolcategory',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'AI Tool Category', 'verbose_name_plural': 'AI Tool Categories'},
        ),
        migrations.AlterModelOptions(
            name='promptlibrary',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='aitool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aitoolcategory',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aitoolcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promptlibrary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='promptcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='promptlibrary',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='ai_center.promptcategory'),
        ),
    ]
