# Generated by Django 4.2.23 on 2026-06-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_center', '0002_alter_aitoolcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promptlibrary',
            options={'ordering': ['title'], 'verbose_name': 'Prompt Library', 'verbose_name_plural': 'Prompt Libraries'},
        ),
    ]
