# Generated by Django 4.2.23 on 2026-10-10 20:41

from django.db import migrations, models
import elearning.services
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='notes_link',
            field=models.URLField(blank=True, help_text="Link to the lesson notes/handout — e.g. a Google Drive share link (set sharing to 'Anyone with the link' so students need no Google account). Nothing is uploaded here.", max_length=500, null=True, validators=[elearning.services.validate_web_link], verbose_name='Lesson notes link (optional)'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='resource_link',
            field=models.URLField(blank=True, help_text="External link to the assignment sheet/file — e.g. a Google Drive share link or a file hosted on the school's cPanel. Nothing is uploaded here.", max_length=500, null=True, validators=[elearning.services.validate_web_link], verbose_name='Assignment file link (optional)'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submission_link',
            field=models.URLField(help_text='Link to your completed work (Google Drive, cPanel file link, etc.)', max_length=500, validators=[elearning.services.validate_web_link]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text="Paste the YouTube link. Set the video to 'Unlisted' (not 'Private') so students can watch without a Google account.", null=True, verbose_name='YouTube video link'),
        ),
    ]
