# Generated by Django 4.2.23 on 2026-10-10 22:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import elearning.lessonnotes.links


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0003_alter_schoolidentity_address_line_1_and_more'),
        ('elearning', '0002_alter_reply_options_lesson_notes_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='Subject')),
                ('academic_session', models.CharField(help_text='e.g. 2026/2027', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{4}/\\d{4}$', 'Use the format 2026/2027.')])),
                ('term', models.CharField(choices=[('1', 'First Term'), ('2', 'Second Term'), ('3', 'Third Term')], max_length=1)),
                ('week', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('title', models.CharField(blank=True, help_text='Optional — filled in automatically if left blank.', max_length=200)),
                ('doc_link', models.URLField(help_text='Link to your lesson note in Google Docs, Sheets, Slides or Drive.', max_length=500, validators=[elearning.lessonnotes.links.validate_google_note_link], verbose_name='Google Drive link')),
                ('teacher_note', models.TextField(blank=True, max_length=500, verbose_name='Message to the reviewer (optional)')),
                ('status', models.CharField(choices=[('submitted', 'Awaiting review'), ('approved', 'Approved'), ('revision', 'Changes requested')], db_index=True, default='submitted', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remark', models.TextField(blank=True, max_length=1000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elearning_lesson_notes_reviewed', to=settings.AUTH_USER_MODEL)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='curriculum.standard', verbose_name='Class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elearning_lesson_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher lesson note',
                'verbose_name_plural': 'Teacher lesson notes',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonNoteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('edited', 'Edited'), ('resubmitted', 'Resubmitted after changes'), ('approved', 'Approved'), ('revision_requested', 'Changes requested')], max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='elearning.lessonnote')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='lessonnote',
            index=models.Index(fields=['status', '-submitted_at'], name='elearning_l_status_c96afe_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonnote',
            index=models.Index(fields=['teacher', 'status'], name='elearning_l_teacher_a1a431_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonnote',
            constraint=models.UniqueConstraint(fields=('teacher', 'standard', 'subject_name', 'academic_session', 'term', 'week'), name='elearning_lessonnote_unique_slot'),
        ),
    ]
