# Generated by Django 4.2.23 on 2026-07-25 22:44

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Message')),
                ('target_audience', models.CharField(choices=[('TEST', 'Only Me (Testing)'), ('ALL', 'All Users'), ('PARENTS', 'Parents Only'), ('STUDENTS', 'Students Only'), ('STAFF', 'Teachers/Staff Only'), ('ADMINS', 'Admins Only')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=50)),
                ('acc_number', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=50, verbose_name='Bank Name')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
            options={
                'unique_together': {('acc_number', 'bank_name')},
            },
        ),
    ]
