# Generated by Django 4.2.23 on 2026-09-10 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HybridIntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_classroom_url', models.URLField(blank=True, default='https://classroom.google.com/', help_text="Sign-in link for your school's Google Classroom / Workspace for Education domain.")),
                ('google_meet_url', models.URLField(blank=True, default='https://meet.google.com/', help_text='Default Google Meet link/landing page for live classes.')),
                ('google_workspace_admin_url', models.URLField(blank=True, help_text='Google Admin Console link — shown to school admins only.')),
                ('microsoft_teams_url', models.URLField(blank=True, default='https://teams.microsoft.com/', help_text='Sign-in link for Microsoft Teams for Education.')),
                ('microsoft_365_admin_url', models.URLField(blank=True, help_text='Microsoft 365 Admin Center link — shown to school admins only.')),
                ('bulk_sms_enabled', models.BooleanField(default=False, help_text='Turn on to expose the Bulk SMS tile to school admins/teachers.')),
                ('bulk_sms_provider_name', models.CharField(blank=True, help_text="e.g. Termii, KudiSMS, Africa's Talking, Twilio.", max_length=100)),
                ('bulk_sms_provider_url', models.URLField(blank=True, help_text="Link to your Bulk SMS provider's dashboard/portal (if external).")),
                ('zoom_url', models.URLField(blank=True, help_text='Optional Zoom link, if used instead of/alongside Google Meet.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_integration_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hybrid Integration Settings',
                'verbose_name_plural': 'Hybrid Integration Settings',
            },
        ),
    ]
