# Generated by Django 4.2.23 on 2025-12-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(help_text='You can use HTML tags here if needed')),
                ('target_audience', models.CharField(choices=[('TEST', 'Only Me (Testing)'), ('ALL', 'All Users'), ('PARENTS', 'Parents Only'), ('STUDENTS', 'Students Only'), ('STAFF', 'Teachers/Staff Only'), ('ADMINS', 'Admins Only')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
