# Generated by Django 4.2.23 on 2025-12-27 18:53

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Message'),
        ),
    ]
