"""
Django settings for schoolly project.

Generated by 'django-admin startproject' using Django 4.0.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-794v=dtc7_vx4-k7)52ndq#%#+qg1cs*e_q&6x)s%eqiur)n^5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # My portal apps
    'users.apps.UsersConfig',
    'students.apps.StudentsConfig',
    'staff.apps.StaffConfig',
    'curriculum.apps.CurriculumConfig',
    'results.apps.ResultsConfig',
    'pages.apps.PagesConfig',
    'payments.apps.PaymentsConfig',
    'attendance.apps.AttendanceConfig',
    'transport.apps.TransportConfig',
    'cbt.apps.CbtConfig',
    'tickets.apps.TicketsConfig',
    'events.apps.EventsConfig',
    'prep_reports.apps.PrepReportsConfig',
    'ai_center.apps.AiCenterConfig',
    'finance.apps.FinanceConfig',


    # Installed Apps
    'django_ckeditor_5',
    'storages',
    'crispy_forms',
    'crispy_bootstrap4',
    'import_export',
    'mathfilters',
    'wkhtmltopdf',
    'bootstrap_datepicker_plus',
    'django_filters',
    'embed_video',
    'djrichtextfield',
    'tinymce',
    'django_cleanup.apps.CleanupConfig',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'schoolly.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'students.context_processors.student_context', # added by me after creating students/context_processor.py
                'transport.context_processors.school_identity', # Add this line
                'tickets.context_processors.unread_tickets_count', 


            ],
        },
    },
]

WSGI_APPLICATION = 'schoolly.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# # LOGIN_REDIRECT_URL = 'pages:portal-home'
# LOGIN_REDIRECT_URL = '/dashboard/'

# # LOGIN_URL = 'users:login'
# LOGIN_URL = '/users/login/'

LOGIN_REDIRECT_URL = 'pages:portal-home' # Redirect students to their dashboard after login
LOGOUT_REDIRECT_URL = '/' # Redirect to home page after logout (or login page)
LOGIN_URL = '/users/login/' # URL name of your login page

# # Email settings for the CBT app
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# DEFAULT_FROM_EMAIL = 'no-reply@kwikschools.com'
# ADMIN_EMAIL = 'contact@kwikschools.com'

# Switch back to the standard SMTP backend
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'kwikschools@gmail.com'
EMAIL_HOST_PASSWORD = 'fsme syad fqgx cdqp'  # Paste your 16-digit App Password here

# Note: Gmail will often overwrite the "From" address to your Gmail address
DEFAULT_FROM_EMAIL = 'kwikschools@gmail.com'




# # EMAIL SETTINGS FOR SMTP2GO
# # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' 
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'   #== USED FOR TESTING

# # 2. SMTP2GO Connection Details
# EMAIL_HOST = 'mail.smtp2go.com'
# # EMAIL_HOST = 'mail-eu.smtp2go.com'
# EMAIL_PORT = 2525  # You can also use 587 or 8025
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'kwikschools' # This is usually your email or a specific SMTP user
# EMAIL_HOST_PASSWORD = 'Christ4ALL@1971'

# # 3. This must be a VERIFIED sender in your SMTP2GO dashboard
# DEFAULT_FROM_EMAIL = 'contact@kwikschools.com'

# # WORKING EMAIL SETTINGS
# # 1. Anymail settings
# ANYMAIL = {
#     # "SENDGRID_API_KEY": "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",
#     "SMTP2GO_API_KEYapi": "879A5AD399F5415C848EA37EF7204F04"
# }
# # EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"
# EMAIL_BACKEND = "anymail.backends.smtp2go.EmailBackend"  # for SMTP2GO

# # 2. Global Email settings
# # This MUST match the email you verified in SendGrid
# DEFAULT_FROM_EMAIL = "Kwikschools <contact@kwikschools.com>" 
# SERVER_EMAIL = "contact@kwikschools.com" # For error logs

# ============================================================

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"
CRISPY_TEMPLATE_PACK = 'bootstrap4'

CKEDITOR_UPLOAD_PATH = "uploads/"



IMPORT_EXPORT_IMPORT_PERMISSION_CODE = 'delete' 
IMPORT_EXPORT_EXPORT_PERMISSION_CODE = 'delete'


DJRICHTEXTFIELD_CONFIG = {
    'js': ['//cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js'],
    'init_template': 'djrichtextfield/init/tinymce.js',
    'settings': {
        'menubar': False,
        'plugins': 'link image',
        'toolbar': 'bold italic | link image | removeformat',
        'width': 700
    }
}


TINYMCE = {
    "default": {
        "api_key": "3esfs97p8ehu9haq4lcn4xnoettt6z0qudwnz75g5rfddxrt", # <--- IMPORTANT: Replace with your actual TinyMCE API Key
                                            # Get it from https://www.tiny.cloud/
        "menubar": "file edit view insert format tools table help",
        "plugins": (
            "advlist", "autolink", "lists", "link", "image", "charmap", "preview",
            "anchor", "searchreplace", "visualblocks", "code", "fullscreen",
            "insertdatetime", "media", "table", "code", "paste", "help", "wordcount"
        ),
        "toolbar": (
            "undo redo | blocks | fontfamily fontsize | "
            "bold italic backcolor | alignleft aligncenter "
            "alignright alignjustify | bullist numlist outdent indent | "
            "removeformat | help"
        ),
        "height": 400,
        "width": "100%",
        "branding": False, # Set to True if you want TinyMCE branding (defaults to True)
        "content_css": [ # Optional: Link to your site's CSS for consistent styling
            "/static/css/tinymce-content.css", # Example path
        ],
        "browser_spellcheck": True,
        "contextmenu": "link image table",
        "custom_undo_redo_levels": 10,
        "extended_valid_elements": "script[language|type|src|charset],img[*]", # Example: allow script and img attributes
    }
}




CKEDITOR_5_CONFIGS = {
    'extends': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
            '|', 'bulletedList', 'numberedList', 'blockQuote',
            '|', 'insertImage', 'mediaEmbed', 'sourceEditing', '|', 'undo', 'redo'
        ],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:alignRight'],
            'styles': ['alignLeft', 'alignCenter', 'alignRight']
        },
    },
}