# Generated by Django 4.2.23 on 2026-07-25 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('curriculum', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepAcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_term_begins', models.DateField(blank=True, help_text="Date printed on report card: 'Next term begins …'", null=True)),
                ('days_school_opened', models.PositiveSmallIntegerField(default=0, help_text='Number of days school opened this term (report card header).')),
                ('session', models.ForeignKey(help_text='Academic session — select from Curriculum → Sessions.', on_delete=django.db.models.deletion.PROTECT, related_name='prep_periods', to='curriculum.session')),
                ('term', models.ForeignKey(help_text='Term within that session — select from Curriculum → Terms.', on_delete=django.db.models.deletion.PROTECT, related_name='prep_periods', to='curriculum.term')),
            ],
            options={
                'verbose_name': 'Prep Academic Period',
                'verbose_name_plural': 'Prep Academic Periods',
                'ordering': ['-session__start_date', 'term__start_date'],
                'unique_together': {('session', 'term')},
            },
        ),
        migrations.CreateModel(
            name='PrepClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('standard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prep_config', to='curriculum.standard', verbose_name='Class / Standard')),
            ],
            options={
                'verbose_name': 'Prep Class Configuration',
                'verbose_name_plural': 'Prep Class Configurations',
                'ordering': ['standard__name'],
            },
        ),
        migrations.CreateModel(
            name='RatingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False, help_text='If checked, new prep classes will use this scale.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rating Scale',
                'verbose_name_plural': 'Rating Scales',
            },
        ),
        migrations.CreateModel(
            name='RatingColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. A, B, Apprentice, Expert', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='prep_reports.ratingscale')),
            ],
            options={
                'verbose_name': 'Rating Column',
                'verbose_name_plural': 'Rating Columns',
                'ordering': ['scale', 'order'],
                'unique_together': {('scale', 'label')},
            },
        ),
        migrations.CreateModel(
            name='PrepSubjectSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Observable skill / learning objective statement.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('prep_class', models.ForeignKey(blank=True, help_text='Leave blank to apply to ALL prep classes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='prep_reports.prepclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_skills', to='curriculum.subject')),
            ],
            options={
                'verbose_name': 'Prep Subject Skill',
                'verbose_name_plural': 'Prep Subject Skills',
                'ordering': ['subject', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PrepReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_present', models.PositiveSmallIntegerField(default=0)),
                ('days_absent', models.PositiveSmallIntegerField(default=0)),
                ('class_teacher_comment', models.TextField(blank=True)),
                ('head_teacher_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_prep_reports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prep_reports', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='prep_reports.prepacademicperiod')),
                ('prep_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='prep_reports.prepclass')),
                ('promoted_to', models.ForeignKey(blank=True, help_text='Class pupil is promoted to (leave blank if not yet decided).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_prep_students', to='curriculum.standard')),
                ('rating_scale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='prep_reports.ratingscale')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_report_cards', to='students.student')),
            ],
            options={
                'verbose_name': 'Prep Report Card',
                'verbose_name_plural': 'Prep Report Cards',
                'ordering': ['-period__session__start_date', 'period__term__start_date', 'student__user__last_name'],
                'unique_together': {('student', 'period', 'prep_class')},
            },
        ),
        migrations.CreateModel(
            name='PrepDomainTraitTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('psychomotor', 'Psychomotor Domain'), ('affective', 'Affective / Cognitive Domain')], max_length=20)),
                ('trait_name', models.CharField(max_length=100)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('prep_class', models.ForeignKey(blank=True, help_text='Leave blank for global (all prep classes).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_trait_templates', to='prep_reports.prepclass')),
            ],
            options={
                'verbose_name': 'Domain Trait Template',
                'verbose_name_plural': 'Domain Trait Templates',
                'ordering': ['domain', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PrepSkillEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_comment', models.TextField(blank=True, help_text='Optional teacher comment for this subject.')),
                ('entered_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prep_skill_entries', to=settings.AUTH_USER_MODEL)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_entries', to='prep_reports.prepreportcard')),
                ('selected_column', models.ForeignKey(blank=True, help_text='The column ticked by the teacher (null = not yet rated).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='prep_reports.ratingcolumn')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='prep_reports.prepsubjectskill')),
            ],
            options={
                'verbose_name': 'Prep Skill Entry',
                'verbose_name_plural': 'Prep Skill Entries',
                'ordering': ['skill__subject', 'skill__order'],
                'unique_together': {('report_card', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='PrepDomainRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('psychomotor', 'Psychomotor Domain'), ('affective', 'Affective / Cognitive Domain')], max_length=20)),
                ('trait_name', models.CharField(max_length=100)),
                ('rating_text', models.CharField(blank=True, help_text='e.g. Excellent, Distinction, 4, 5', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('report_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_ratings', to='prep_reports.prepreportcard')),
            ],
            options={
                'verbose_name': 'Prep Domain Rating',
                'verbose_name_plural': 'Prep Domain Ratings',
                'ordering': ['domain', 'order'],
                'unique_together': {('report_card', 'domain', 'trait_name')},
            },
        ),
    ]
