# Generated by Django 4.2.23 on 2026-05-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_remove_term_only_one_current_term_and_more'),
        ('prep_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepacademicperiod',
            options={'ordering': ['-session__start_date', 'term__start_date'], 'verbose_name': 'Prep Academic Period', 'verbose_name_plural': 'Prep Academic Periods'},
        ),
        migrations.AlterModelOptions(
            name='prepreportcard',
            options={'ordering': ['-period__session__start_date', 'period__term__start_date', 'student__user__last_name'], 'verbose_name': 'Prep Report Card', 'verbose_name_plural': 'Prep Report Cards'},
        ),
        migrations.RemoveField(
            model_name='prepacademicperiod',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='prepacademicperiod',
            name='is_current',
        ),
        migrations.RemoveField(
            model_name='prepacademicperiod',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='prepacademicperiod',
            name='days_school_opened',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of days school opened this term (report card header).'),
        ),
        migrations.AlterField(
            model_name='prepacademicperiod',
            name='next_term_begins',
            field=models.DateField(blank=True, help_text="Date printed on report card: 'Next term begins …'", null=True),
        ),
        migrations.AlterField(
            model_name='prepacademicperiod',
            name='session',
            field=models.ForeignKey(help_text='Academic session — select from Curriculum → Sessions.', on_delete=django.db.models.deletion.PROTECT, related_name='prep_periods', to='curriculum.session'),
        ),
        migrations.AlterField(
            model_name='prepacademicperiod',
            name='term',
            field=models.ForeignKey(help_text='Term within that session — select from Curriculum → Terms.', on_delete=django.db.models.deletion.PROTECT, related_name='prep_periods', to='curriculum.term'),
        ),
    ]
