# Generated by Django 4.2.23 on 2026-09-06 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_asset',
            field=models.BooleanField(default=False, help_text='Tick for trackable individual assets (laptops, projectors) that get issued to a specific person, as opposed to bulk consumables (paper, chalk).'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='qr_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='ItemCustody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('held_by_name', models.CharField(help_text='Name of staff/student/department currently holding this item.', max_length=150)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('issue_notes', models.TextField(blank=True, help_text='Condition at issue, purpose, etc.')),
                ('return_notes', models.TextField(blank=True, help_text='Condition at return, any damage noted.')),
                ('held_by_user', models.ForeignKey(blank=True, help_text='Optional: link to a system user account, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_in_custody', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_issued', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_records', to='inventory.inventoryitem')),
                ('received_by', models.ForeignKey(blank=True, help_text='Staff member who processed the return.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_received_back', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Item Custody Records',
                'ordering': ['-issued_date'],
            },
        ),
    ]
