# Generated by Django 4.2.23 on 2026-09-10 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_paymentnotification_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_inventoryitem_is_asset_inventoryitem_qr_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcustody',
            name='assigned_location',
            field=models.CharField(blank=True, help_text="Where the item currently sits — e.g. 'Basic 3 Classroom', 'Science Lab', 'Admin Office'. Leave blank if it moves with the person (e.g. a phone).", max_length=150),
        ),
        migrations.AlterField(
            model_name='itemcustody',
            name='held_by_name',
            field=models.CharField(help_text='Person responsible — staff, student, or department name.', max_length=150),
        ),
        migrations.AlterField(
            model_name='itemcustody',
            name='held_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_in_custody', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemcustody',
            name='issue_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemcustody',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_received_back', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemcustody',
            name='return_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text="Only relevant for 'Stock In' — who the item was purchased from.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.vendor'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
