# Generated by Django 4.2.23 on 2026-09-10 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_paymentnotification_notes'),
        ('inventory', '0003_itemcustody_assigned_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='to_location',
            field=models.CharField(blank=True, help_text="For 'Internal Transfer' — the item's new location. Updates the item's recorded location.", max_length=150),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='issued_to',
            field=models.CharField(blank=True, help_text="Person/department this movement concerns — e.g. 'Mrs. Bello', 'JSS2 Science Lab'.", max_length=150),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In (Purchase/Donation)'), ('out', 'Stock Out (Used/Consumed)'), ('transfer', 'Internal Transfer (Location/Personnel)'), ('damaged', 'Damaged/Lost'), ('adjustment', 'Manual Adjustment')], max_length=15),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text="Only for 'Stock In' — who the item was purchased from.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.vendor'),
        ),
    ]
