# Generated by Django 4.2.23 on 2025-12-21 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=50)),
                ('number_of_questions', models.IntegerField()),
                ('time', models.IntegerField(help_text='Duration in minutes')),
                ('required_score_to_pass', models.IntegerField(help_text='Percentage (e.g., 50)')),
                ('active', models.BooleanField(default=False)),
                ('examination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='results.examination')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbt_session', to='curriculum.session')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_exams', to='curriculum.standard')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('passed', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Question Text')),
                ('image_url', models.URLField(blank=True, help_text="Paste the Google Drive 'Share' link here.", null=True)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice (A, B, C, D)'), ('SHORT', 'Short Answer (Fill in)')], default='MCQ', max_length=10)),
                ('option_a', models.CharField(blank=True, max_length=200, null=True)),
                ('option_b', models.CharField(blank=True, max_length=200, null=True)),
                ('option_c', models.CharField(blank=True, max_length=200, null=True)),
                ('option_d', models.CharField(blank=True, max_length=200, null=True)),
                ('correct_answer', models.CharField(help_text='For MCQ: enter A, B, C, or D. For Short Answer: enter the correct word.', max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.question')),
            ],
        ),
    ]
