# Generated by Django 4.2.23 on 2026-07-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('cbt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cbt_session', to='curriculum.session'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_exams', to='curriculum.standard'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.subject'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.quiz'),
        ),
        migrations.AddField(
            model_name='examination',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.session'),
        ),
        migrations.AddField(
            model_name='examination',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculum.standard'),
        ),
        migrations.AddField(
            model_name='examination',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='curriculum.term'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.question'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('examination', 'subject', 'term', 'session'), name='unique_quiz_per_exam_context'),
        ),
        migrations.AlterUniqueTogether(
            name='examination',
            unique_together={('name', 'term', 'date')},
        ),
    ]
