# Generated by Django 4.2.23 on 2026-02-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
