# Generated by Django 4.2.23 on 2026-07-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examination',
            options={'ordering': ['term__start_date', 'date', 'name'], 'verbose_name': 'Examination Settings', 'verbose_name_plural': 'Examination Settings'},
        ),
    ]
