# Generated by Django 4.2.23 on 2026-02-11 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbt', '0002_quizattempt_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
