# Generated by Django 4.2.23 on 2026-02-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0003_quizattempt_cancelled_at_quizattempt_cancelled_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresult',
            options={},
        ),
        migrations.AddField(
            model_name='quizresult',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
