# Generated by Django 4.2.23 on 2026-02-11 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0004_alter_quizresult_options_quizresult_cancelled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
