# Generated by Django 4.2.23 on 2026-02-12 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0005_rename_timestamp_quizresult_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizresult',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
