# Generated by Django 4.2.23 on 2026-07-27 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Creche-Gold, Basic 1-A', max_length=100)),
            ],
            options={
                'verbose_name': 'Class Group',
                'verbose_name_plural': 'Class Groups',
                'ordering': ['standard'],
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('identity_label', models.CharField(blank=True, help_text='e.g. Primary, Secondary, or Main', max_length=50, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Fallback identity if no specific class identity is set.')),
                ('address_line_1', models.CharField(max_length=60)),
                ('address_line_2', models.CharField(blank=True, max_length=60, null=True)),
                ('phone1', models.CharField(max_length=11)),
                ('phone2', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(default='school_logo.jpg', help_text='must not exceed 180px by 180px in size', upload_to='official_pics')),
                ('signature', models.ImageField(blank=True, help_text='must not exceed 180px by 180px in size', null=True, upload_to='official_pics')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'School Identity Setting',
                'verbose_name_plural': 'School Identity Settings',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('desc', models.TextField(blank=True, max_length=100)),
                ('is_current', models.BooleanField(default=False, help_text='Check this box if this is the current session')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sessions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('promotion_order', models.IntegerField(blank=True, help_text='Order of classes for promotion (e.g., 0 for the lowest class, 1 for Basic 1, 2 for Basic 2)', null=True, unique=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Standard (GRADE LEVELS)',
                'verbose_name_plural': 'Standards (GRADE LEVELS)',
                'ordering': ['promotion_order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': ' Subjects',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, help_text='check the box if the term is current term in the current session')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='curriculum.session')),
            ],
            options={
                'ordering': ['session', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='StandardIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.schoolidentity')),
                ('standard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_mapping', to='curriculum.standard')),
            ],
            options={
                'verbose_name': 'Class-Identity Mapping',
                'verbose_name_plural': 'Class-Identity Mappings',
            },
        ),
    ]
