# Generated by Django 4.2.23 on 2026-07-27 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='form_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_class', to='staff.teacher'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='only_one_current_session'),
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_holidays', to='curriculum.term'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='form_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='staff.teacher'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='curriculum.standard'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='only_one_current_term_can_be_active'),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('name', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together={('term', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('standard', 'name')},
        ),
    ]
