# Generated by Django 4.2.23 on 2025-08-11 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standard',
            options={'ordering': ['promotion_order'], 'verbose_name': 'Standard (GRADE LEVELS)', 'verbose_name_plural': 'Standards (GRADE LEVELS)'},
        ),
        migrations.AddField(
            model_name='standard',
            name='form_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_class', to='staff.teacher'),
        ),
    ]
