# Generated by Django 4.2.23 on 2025-07-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AddField(
            model_name='session',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
