# Generated by Django 4.2.23 on 2025-07-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='description'),
        ),
    ]
