# Generated by Django 4.2.23 on 2025-08-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='standard',
        ),
    ]
