# Generated by Django 4.2.23 on 2026-04-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(help_text='Enter the lesson topic (e.g. Heat Energy, Algebraic Expressions)', max_length=250, verbose_name='Topic'),
        ),
    ]
