# Generated by Django 4.2.23 on 2025-09-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClassPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ZOOM', 'Zoom'), ('MEET', 'Google Meet'), ('TEAMS', 'Microsoft Teams')], default='ZOOM', max_length=5)),
                ('meeting_link', models.URLField(help_text="The full link for this class's recurring meeting (e.g., Zoom join link)")),
                ('is_active', models.BooleanField(default=True, help_text='Only active links will be visible to students.')),
                ('current_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_links', to='curriculum.standard', verbose_name='Related Class')),
            ],
            options={
                'verbose_name': 'Class Online Meeting Link',
                'verbose_name_plural': 'Class Online Meeting Links',
                'unique_together': {('current_class', 'platform')},
            },
        ),
    ]
