# Generated by Django 4.2.23 on 2025-07-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_session_options_session_is_current'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standard',
            options={'ordering': ['name'], 'verbose_name': 'Standard', 'verbose_name_plural': 'Standards'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Subjects', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
