# Generated by Django 4.2.23 on 2025-08-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_remove_subject_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.elearningsubject'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_current',
            field=models.BooleanField(default=False, help_text='check the box if the session is current'),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='is_current',
            field=models.BooleanField(default=False, help_text='check the box if the term is current term in the current session'),
        ),
        migrations.AlterUniqueTogether(
            name='elearningsubject',
            unique_together={('name', 'standard')},
        ),
    ]
