# Generated by Django 4.2.23 on 2025-08-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_standard_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolidentity',
            name='signature',
            field=models.ImageField(blank=True, default='school_logo.jpg', help_text='must not exceed 180px by 180px in size', null=True, upload_to='official_pics'),
        ),
    ]
