# Generated by Django 4.2.23 on 2025-08-12 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('curriculum', '0002_alter_standard_options_standard_form_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={'ordering': ['standard__promotion_order', 'promotion_order'], 'verbose_name': 'Class Group', 'verbose_name_plural': 'Class Groups'},
        ),
        migrations.AddField(
            model_name='classgroup',
            name='form_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='staff.teacher'),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='promotion_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='standard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='curriculum.standard'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.CharField(help_text='e.g., Creche-Gold, Basic 1-A', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('standard', 'name')},
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='slug',
        ),
    ]
