# Generated by Django 4.2.23 on 2026-03-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolidentity',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schoolidentity',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
