# Generated by Django 4.2.23 on 2026-10-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolidentity',
            name='address_line_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolidentity',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
