# Generated by Django 4.2.23 on 2025-09-30 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_onlineclassplatform'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectOnlineMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ZOOM', 'Zoom'), ('MEET', 'Google Meet'), ('TEAMS', 'Microsoft Teams')], default='ZOOM', max_length=5)),
                ('meeting_link', models.URLField(help_text="The full join URL for this subject's online class (e.g., Zoom link)")),
                ('is_active', models.BooleanField(default=True, help_text='Only active links will be visible to students.')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_meetings', to='curriculum.elearningsubject', verbose_name='E-Learning Subject')),
            ],
            options={
                'verbose_name': 'Subject Online Meeting Link',
                'verbose_name_plural': 'Subject Online Meeting Links',
                'ordering': ['subject__name', 'platform'],
                'unique_together': {('subject', 'platform')},
            },
        ),
        migrations.DeleteModel(
            name='OnlineClassPlatform',
        ),
    ]
