# Generated by Django 4.2.23 on 2026-07-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_publicholiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['session', 'start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('name', 'session')},
        ),
    ]
