# Generated by Django 4.2.23 on 2026-04-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_lesson_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolidentity',
            options={'verbose_name': 'School Identity Setting', 'verbose_name_plural': 'School Identity Settings'},
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='identity_label',
            field=models.CharField(blank=True, help_text='e.g. Primary, Secondary, or Main', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schoolidentity',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Fallback identity if no specific class identity is set.'),
        ),
        migrations.CreateModel(
            name='StandardIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.schoolidentity')),
                ('standard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_mapping', to='curriculum.standard')),
            ],
            options={
                'verbose_name': 'Class-Identity Mapping',
                'verbose_name_plural': 'Class-Identity Mappings',
            },
        ),
    ]
