# Generated by Django 4.2.23 on 2025-08-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_classgroup_name_alter_lesson_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standard',
            options={'ordering': ['name'], 'verbose_name': 'Standard (GRADE LEVELS)', 'verbose_name_plural': 'Standards (GRADE LEVELS)'},
        ),
        migrations.AddField(
            model_name='subject',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examsubjects', to='curriculum.standard'),
        ),
    ]
