# Generated by Django 4.2.23 on 2025-10-15 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_subjectonlinemeeting_delete_onlineclassplatform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectOnlineMeeting',
        ),
    ]
