# Generated by Django 4.2.23 on 2026-04-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_term_options_alter_term_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='term',
            name='only_one_current_term',
        ),
        migrations.AlterField(
            model_name='session',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Check this box if this is the current session'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='only_one_current_session'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='only_one_current_term_can_be_active'),
        ),
    ]
