# Generated by Django 4.2.23 on 2025-09-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='audience',
            field=models.CharField(blank=True, choices=[('all', 'All Users'), ('teachers', 'Teachers'), ('students', 'Students')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_broadcast',
            field=models.BooleanField(default=False),
        ),
    ]
