# Generated by Django 4.2.23 on 2025-07-17 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(blank=True, help_text='Could be Bus Number', max_length=8, null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('direction', models.CharField(blank=True, max_length=200)),
                ('driver', models.CharField(blank=True, max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('staff_in_charge', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_staff', to='staff.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentOnRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='transport.route')),
                ('student', models.ForeignKey(help_text='The student associated with this route.', on_delete=django.db.models.deletion.CASCADE, related_name='studentonroute', to='students.student')),
            ],
            options={
                'ordering': ['student'],
                'unique_together': {('student', 'route')},
            },
        ),
    ]
