# Generated by Django 4.2.23 on 2026-07-25 22:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(blank=True, help_text='Could be Bus Number', max_length=8, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('direction', models.CharField(blank=True, max_length=200)),
                ('bus_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Bus Fare', max_digits=15, null=True)),
                ('driver', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Driver Name')),
                ('driver_phone', models.CharField(blank=True, max_length=11)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('staff_in_charge', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_staff', to='staff.teacher')),
            ],
            options={
                'verbose_name': 'Bus Routes & Fares',
                'verbose_name_plural': 'Bus Routes & Fares',
                'ordering': ['route_id'],
            },
        ),
        migrations.CreateModel(
            name='StudentOnRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Is the student currently active on this route?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='transport.route')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_enrollments', to='curriculum.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_enrollments', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_enrollments', to='curriculum.term')),
            ],
            options={
                'verbose_name': 'Student Bus Enrollment',
                'verbose_name_plural': 'Students Bus Enrollments',
                'unique_together': {('student', 'route', 'session', 'term')},
            },
        ),
        migrations.CreateModel(
            name='BusPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid for this transaction.', max_digits=15)),
                ('payment_date', models.DateField(default=datetime.date.today, verbose_name='Payment Date')),
                ('is_approved', models.BooleanField(default=False, help_text='Check if this payment is confirmed.')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment'), ('online_gateway', 'Online Gateway')], help_text='The method used for the payment.', max_length=50, null=True)),
                ('short_note', models.CharField(blank=True, help_text='Any additional notes about the payment or payee.', max_length=255, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transport.studentonroute')),
            ],
        ),
    ]
