# Generated by Django 4.2.23 on 2025-09-28 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buspayment',
            name='payment_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Payment Date'),
        ),
    ]
