# Generated by Django 4.2.23 on 2025-08-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='driver',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Driver Name'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.CharField(blank=True, help_text='Could be Bus Number', max_length=8, null=True, unique=True),
        ),
    ]
