# Generated by Django 4.2.23 on 2025-07-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentonroute',
            old_name='created',
            new_name='signup_date',
        ),
    ]
