# Generated by Django 4.2.23 on 2025-08-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buspayment',
            name='short_note',
            field=models.CharField(blank=True, help_text='Any additional notes about the payment or payee.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='buspayment',
            name='payment_date',
            field=models.DateField(verbose_name='Payment Date'),
        ),
    ]
