# Generated by Django 4.2.23 on 2025-07-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_rename_created_studentonroute_signup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='bus_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Bus Fare', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='studentonroute',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount Paid For Bus', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='studentonroute',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card Payment'), ('online_gateway', 'Online Gateway')], help_text='The method used for the payment.', max_length=50, null=True),
        ),
    ]
