# Generated by Django 4.2.23 on 2025-08-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_alter_route_driver_alter_route_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['route_id'], 'verbose_name': 'Bus Routes & Fares', 'verbose_name_plural': 'Bus Routes & Fares'},
        ),
        migrations.AlterModelOptions(
            name='studentonroute',
            options={'ordering': ['student'], 'verbose_name': 'Students On Bus Route', 'verbose_name_plural': 'Students On Bus Route'},
        ),
        migrations.AddField(
            model_name='studentonroute',
            name='is_active_on_bus',
            field=models.BooleanField(default=False, help_text='Check if student is ACTIVE on bus Uncheck If Student in INACTIVE'),
        ),
        migrations.AlterField(
            model_name='studentonroute',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Check if payment is confirmed.'),
        ),
    ]
