# Generated by Django 4.2.23 on 2025-07-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_route_bus_fee_route_driver_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentonroute',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payment Date'),
        ),
    ]
