# Generated by Django 4.2.23 on 2025-08-07 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_studentonroute_payment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['route_id'], 'verbose_name': 'Route/Fare'},
        ),
    ]
