# Generated by Django 4.2.23 on 2026-07-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('students', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesummary',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.session'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='students.student'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.term'),
        ),
        migrations.AddField(
            model_name='attendanceconfiguration',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.session'),
        ),
        migrations.AddField(
            model_name='attendanceconfiguration',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.term'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('student', 'session', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='attendanceconfiguration',
            unique_together={('session', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
