# Generated by Django 4.2.23 on 2026-07-25 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=150)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_holidays', to='curriculum.term')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('term', 'date')},
            },
        ),
    ]
