# Generated by Django 4.2.23 on 2026-10-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancesummary',
            options={'verbose_name': 'Attendance Summary', 'verbose_name_plural': 'Attendance Summaries'},
        ),
    ]
