# Generated by Django 4.2.23 on 2026-07-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_publicholiday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicHoliday',
        ),
    ]
