# Generated by Django 4.2.23 on 2026-07-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_delete_publicholiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesummary',
            name='days_absent',
        ),
    ]
